[build]
builder = "NIXPACKS"
watchPatterns = ["src/**"]
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[config]
PORT = 3001

[[services]]
internal_port = 3001
protocol = "http"
auto_domain_suffix = "beehiiv-auth-api"

[[services.ports]]
port = 80
handlers = ["http"]

[[services.ports]]
port = 443
handlers = ["tls", "http"] 