services:
  - type: web
    name: beehiiv-auth-api
    env: node
    plan: free  # Change this based on your needs
    region: oregon  # or another supported region
    branch: main  # Adjust if deploying from a different branch
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
